import enum

class StatsList:
    def __init__(self, hp, attack, defense, special_attack, special_defense, speed) -> None:
        self.hp = hp
        self.attack = attack
        self.defense = defense
        self.special_attack = special_attack
        self.special_defense = special_defense
        self.speed = speed

class Type(enum.Enum):
    NORMAL = 0
    FIRE = 1
    WATER = 2
    ELECTRIC = 3
    GRASS = 4
    ICE = 5
    FIGHTING = 6
    POISON = 7
    GROUND = 8
    FLYING = 9
    PSYCHIC = 10
    BUG = 11
    ROCK = 12
    GHOST = 13
    DRAGON = 14
    DARK = 15
    STEEL = 16

    def __str__(self) -> str:
        return self.name

class Ability:
    def __init__(self) -> None:
        ...

class LevelingRate:
    def __init__(self) -> None:
        pass

COMBOS = {
    ('NORMAL', None): {'FIGHTING': 2, 'GHOST': 0},
    ('NORMAL', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 0, 'STEEL': 0.5},
    ('NORMAL', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 2, 'GHOST': 0, 'STEEL': 0.5},
    ('NORMAL', 'ELECTRIC'): {'ELECTRIC': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'GHOST': 0, 'STEEL': 0.5},
    ('NORMAL', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'GHOST': 0},
    ('NORMAL', 'ICE'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 4, 'ROCK': 2, 'GHOST': 0, 'STEEL': 2},
    ('NORMAL', 'FIGHTING'): {'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 0, 'DARK': 0.5},
    ('NORMAL', 'POISON'): {'GRASS': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'GHOST': 0},
    ('NORMAL', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'ROCK': 0.5, 'GHOST': 0},
    ('NORMAL', 'FLYING'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 0},
    ('NORMAL', 'PSYCHIC'): {'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 0, 'DARK': 2},
    ('NORMAL', 'BUG'): {'FIRE': 2, 'GRASS': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'GHOST': 0},
    ('NORMAL', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'GHOST': 0, 'STEEL': 2},
    ('NORMAL', 'GHOST'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 0, 'DARK': 2},
    ('NORMAL', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'GHOST': 0, 'DRAGON': 2},
    ('NORMAL', 'DARK'): {'FIGHTING': 4, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0, 'DARK': 0.5},
    ('NORMAL', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 0, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('FIRE', None): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('FIRE', 'NORMAL'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 0, 'STEEL': 0.5},
    ('FIRE', 'WATER'): {'FIRE': 0.25, 'ELECTRIC': 2, 'ICE': 0.25, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.25},
    ('FIRE', 'ELECTRIC'): {'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.25},
    ('FIRE', 'GRASS'): {'ELECTRIC': 0.5, 'GRASS': 0.25, 'POISON': 2, 'FLYING': 2, 'ROCK': 2, 'STEEL': 0.5},
    ('FIRE', 'ICE'): {'WATER': 2, 'GRASS': 0.5, 'ICE': 0.25, 'FIGHTING': 2, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 4},
    ('FIRE', 'FIGHTING'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'DARK': 0.5, 'STEEL': 0.5},
    ('FIRE', 'POISON'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.25, 'ICE': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 4, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 2, 'STEEL': 0.5},
    ('FIRE', 'GROUND'): {'FIRE': 0.5, 'WATER': 4, 'ELECTRIC': 0, 'POISON': 0.5, 'GROUND': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('FIRE', 'FLYING'): {'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.25, 'ROCK': 4, 'STEEL': 0.5},
    ('FIRE', 'PSYCHIC'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0.5, 'GROUND': 2, 'PSYCHIC': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('FIRE', 'BUG'): {'WATER': 2, 'GRASS': 0.25, 'ICE': 0.5, 'FIGHTING': 0.5, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 4, 'STEEL': 0.5},
    ('FIRE', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.25, 'WATER': 4, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2},
    ('FIRE', 'GHOST'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 2, 'BUG': 0.25, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('FIRE', 'DRAGON'): {'FIRE': 0.25, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'DRAGON': 2, 'STEEL': 0.5},
    ('FIRE', 'DARK'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'PSYCHIC': 0, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('FIRE', 'STEEL'): {'NORMAL': 0.5, 'WATER': 2, 'GRASS': 0.25, 'ICE': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('WATER', None): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'STEEL': 0.5},
    ('WATER', 'NORMAL'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 2, 'GHOST': 0, 'STEEL': 0.5},
    ('WATER', 'FIRE'): {'FIRE': 0.25, 'ELECTRIC': 2, 'ICE': 0.25, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.25},
    ('WATER', 'ELECTRIC'): {'FIRE': 0.5, 'WATER': 0.5, 'GRASS': 2, 'ICE': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'STEEL': 0.25},
    ('WATER', 'GRASS'): {'WATER': 0.25, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'STEEL': 0.5},
    ('WATER', 'ICE'): {'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.25, 'FIGHTING': 2, 'ROCK': 2},
    ('WATER', 'FIGHTING'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('WATER', 'POISON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('WATER', 'GROUND'): {'FIRE': 0.5, 'ELECTRIC': 0, 'GRASS': 4, 'POISON': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('WATER', 'FLYING'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 4, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('WATER', 'PSYCHIC'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('WATER', 'BUG'): {'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'STEEL': 0.5},
    ('WATER', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.25, 'ELECTRIC': 2, 'GRASS': 4, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5},
    ('WATER', 'GHOST'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('WATER', 'DRAGON'): {'FIRE': 0.25, 'WATER': 0.25, 'DRAGON': 2, 'STEEL': 0.5},
    ('WATER', 'DARK'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 2, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('WATER', 'STEEL'): {'NORMAL': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('ELECTRIC', None): {'ELECTRIC': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'STEEL': 0.5},
    ('ELECTRIC', 'NORMAL'): {'ELECTRIC': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'GHOST': 0, 'STEEL': 0.5},
    ('ELECTRIC', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.25},
    ('ELECTRIC', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'GRASS': 2, 'ICE': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'STEEL': 0.25},
    ('ELECTRIC', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.25, 'GRASS': 0.5, 'ICE': 2, 'POISON': 2, 'BUG': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'ICE'): {'FIRE': 2, 'ELECTRIC': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 2},
    ('ELECTRIC', 'FIGHTING'): {'ELECTRIC': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('ELECTRIC', 'POISON'): {'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('ELECTRIC', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('ELECTRIC', 'FLYING'): {'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'PSYCHIC'): {'ELECTRIC': 0.5, 'FIGHTING': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'BUG'): {'FIRE': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 0.5, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.25},
    ('ELECTRIC', 'GHOST'): {'NORMAL': 0, 'ELECTRIC': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.25, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 2, 'FLYING': 0.5, 'DRAGON': 2, 'STEEL': 0.5},
    ('ELECTRIC', 'DARK'): {'ELECTRIC': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('ELECTRIC', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.25, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('GRASS', None): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2},
    ('GRASS', 'NORMAL'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'GHOST': 0},
    ('GRASS', 'FIRE'): {'ELECTRIC': 0.5, 'GRASS': 0.25, 'POISON': 2, 'FLYING': 2, 'ROCK': 2, 'STEEL': 0.5},
    ('GRASS', 'WATER'): {'WATER': 0.25, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'STEEL': 0.5},
    ('GRASS', 'ELECTRIC'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.25, 'GRASS': 0.5, 'ICE': 2, 'POISON': 2, 'BUG': 2, 'STEEL': 0.5},
    ('GRASS', 'ICE'): {'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'ROCK': 2, 'STEEL': 2},
    ('GRASS', 'FIGHTING'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 4, 'PSYCHIC': 2, 'ROCK': 0.5, 'DARK': 0.5},
    ('GRASS', 'POISON'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'FLYING': 2, 'PSYCHIC': 2},
    ('GRASS', 'GROUND'): {'FIRE': 2, 'ELECTRIC': 0, 'ICE': 4, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'ROCK': 0.5},
    ('GRASS', 'FLYING'): {'FIRE': 2, 'WATER': 0.5, 'GRASS': 0.25, 'ICE': 4, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0, 'FLYING': 2, 'ROCK': 2},
    ('GRASS', 'PSYCHIC'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0.5, 'BUG': 4, 'GHOST': 2, 'DARK': 2},
    ('GRASS', 'BUG'): {'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0.25, 'FLYING': 4, 'BUG': 2, 'ROCK': 2},
    ('GRASS', 'ROCK'): {'NORMAL': 0.5, 'ELECTRIC': 0.5, 'ICE': 2, 'FIGHTING': 2, 'BUG': 2, 'STEEL': 2},
    ('GRASS', 'GHOST'): {'NORMAL': 0, 'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'GROUND': 0.5, 'FLYING': 2, 'GHOST': 2, 'DARK': 2},
    ('GRASS', 'DRAGON'): {'WATER': 0.25, 'ELECTRIC': 0.25, 'GRASS': 0.25, 'ICE': 4, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'DRAGON': 2},
    ('GRASS', 'DARK'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0, 'BUG': 4, 'GHOST': 0.5, 'DARK': 0.5},
    ('GRASS', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'FIGHTING': 2, 'POISON': 0, 'PSYCHIC': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('ICE', None): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 2, 'ROCK': 2, 'STEEL': 2},
    ('ICE', 'NORMAL'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 4, 'ROCK': 2, 'GHOST': 0, 'STEEL': 2},
    ('ICE', 'FIRE'): {'WATER': 2, 'GRASS': 0.5, 'ICE': 0.25, 'FIGHTING': 2, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 4},
    ('ICE', 'WATER'): {'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.25, 'FIGHTING': 2, 'ROCK': 2},
    ('ICE', 'ELECTRIC'): {'FIRE': 2, 'ELECTRIC': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 2},
    ('ICE', 'GRASS'): {'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'ROCK': 2, 'STEEL': 2},
    ('ICE', 'FIGHTING'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('ICE', 'POISON'): {'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('ICE', 'GROUND'): {'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'STEEL': 2},
    ('ICE', 'FLYING'): {'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 4, 'STEEL': 2},
    ('ICE', 'PSYCHIC'): {'FIRE': 2, 'ICE': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('ICE', 'BUG'): {'FIRE': 4, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 4, 'STEEL': 2},
    ('ICE', 'ROCK'): {'NORMAL': 0.5, 'WATER': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 2, 'STEEL': 4},
    ('ICE', 'GHOST'): {'NORMAL': 0, 'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('ICE', 'DRAGON'): {'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 2, 'ROCK': 2, 'DRAGON': 2, 'STEEL': 2},
    ('ICE', 'DARK'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 4, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('ICE', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 4, 'GRASS': 0.5, 'ICE': 0.25, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'DRAGON': 0.5},
    ('FIGHTING', None): {'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5},
    ('FIGHTING', 'NORMAL'): {'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 0, 'DARK': 0.5},
    ('FIGHTING', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'DARK': 0.5, 'STEEL': 0.5},
    ('FIGHTING', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('FIGHTING', 'ELECTRIC'): {'ELECTRIC': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('FIGHTING', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 4, 'PSYCHIC': 2, 'ROCK': 0.5, 'DARK': 0.5},
    ('FIGHTING', 'ICE'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('FIGHTING', 'POISON'): {'GRASS': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 2, 'PSYCHIC': 4, 'BUG': 0.25, 'ROCK': 0.5, 'DARK': 0.5},
    ('FIGHTING', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.25, 'DARK': 0.5},
    ('FIGHTING', 'FLYING'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'DARK': 0.5},
    ('FIGHTING', 'PSYCHIC'): {'FIGHTING': 0.5, 'FLYING': 2, 'ROCK': 0.5, 'GHOST': 2},
    ('FIGHTING', 'BUG'): {'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 4, 'PSYCHIC': 2, 'BUG': 0.5, 'DARK': 0.5},
    ('FIGHTING', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('FIGHTING', 'GHOST'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 0.5, 'GHOST': 2},
    ('FIGHTING', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 2, 'DARK': 0.5},
    ('FIGHTING', 'DARK'): {'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 0, 'ROCK': 0.5, 'GHOST': 0.5, 'DARK': 0.25},
    ('FIGHTING', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'BUG': 0.25, 'ROCK': 0.25, 'DRAGON': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('POISON', None): {'GRASS': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5},
    ('POISON', 'NORMAL'): {'GRASS': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'GHOST': 0},
    ('POISON', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.25, 'ICE': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 4, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 2, 'STEEL': 0.5},
    ('POISON', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('POISON', 'ELECTRIC'): {'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('POISON', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'FLYING': 2, 'PSYCHIC': 2},
    ('POISON', 'ICE'): {'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('POISON', 'FIGHTING'): {'GRASS': 0.5, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 2, 'PSYCHIC': 4, 'BUG': 0.25, 'ROCK': 0.5, 'DARK': 0.5},
    ('POISON', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.25, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5},
    ('POISON', 'FLYING'): {'ELECTRIC': 2, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.25, 'POISON': 0.5, 'GROUND': 0, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 2},
    ('POISON', 'PSYCHIC'): {'GRASS': 0.5, 'FIGHTING': 0.25, 'POISON': 0.5, 'GROUND': 2, 'GHOST': 2, 'DARK': 2},
    ('POISON', 'BUG'): {'FIRE': 2, 'GRASS': 0.25, 'FIGHTING': 0.25, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 2},
    ('POISON', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'POISON': 0.25, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 2},
    ('POISON', 'GHOST'): {'NORMAL': 0, 'GRASS': 0.5, 'FIGHTING': 0, 'POISON': 0.25, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'GHOST': 2, 'DARK': 2},
    ('POISON', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'DRAGON': 2},
    ('POISON', 'DARK'): {'GRASS': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 0, 'GHOST': 0.5, 'DARK': 0.5},
    ('POISON', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.25, 'ICE': 0.5, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.25, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('GROUND', None): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'POISON': 0.5, 'ROCK': 0.5},
    ('GROUND', 'NORMAL'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'ROCK': 0.5, 'GHOST': 0},
    ('GROUND', 'FIRE'): {'FIRE': 0.5, 'WATER': 4, 'ELECTRIC': 0, 'POISON': 0.5, 'GROUND': 2, 'BUG': 0.5, 'STEEL': 0.5},
    ('GROUND', 'WATER'): {'FIRE': 0.5, 'ELECTRIC': 0, 'GRASS': 4, 'POISON': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('GROUND', 'ELECTRIC'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('GROUND', 'GRASS'): {'FIRE': 2, 'ELECTRIC': 0, 'ICE': 4, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'ROCK': 0.5},
    ('GROUND', 'ICE'): {'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'STEEL': 2},
    ('GROUND', 'FIGHTING'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.25, 'DARK': 0.5},
    ('GROUND', 'POISON'): {'WATER': 2, 'ELECTRIC': 0, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.25, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5},
    ('GROUND', 'FLYING'): {'WATER': 2, 'ELECTRIC': 0, 'ICE': 4, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 0, 'BUG': 0.5},
    ('GROUND', 'PSYCHIC'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 0.5, 'GHOST': 2, 'DARK': 2},
    ('GROUND', 'BUG'): {'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 0.5, 'FLYING': 2},
    ('GROUND', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 4, 'ELECTRIC': 0, 'GRASS': 4, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.25, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 0.5, 'STEEL': 2},
    ('GROUND', 'GHOST'): {'NORMAL': 0, 'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.25, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 2, 'DARK': 2},
    ('GROUND', 'DRAGON'): {'FIRE': 0.5, 'ELECTRIC': 0, 'ICE': 4, 'POISON': 0.5, 'ROCK': 0.5, 'DRAGON': 2},
    ('GROUND', 'DARK'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 0.5, 'GHOST': 0.5, 'DARK': 0.5},
    ('GROUND', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.25, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('FLYING', None): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2},
    ('FLYING', 'NORMAL'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 0},
    ('FLYING', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.25, 'ROCK': 4, 'STEEL': 0.5},
    ('FLYING', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 4, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('FLYING', 'ELECTRIC'): {'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('FLYING', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'GRASS': 0.25, 'ICE': 4, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0, 'FLYING': 2, 'ROCK': 2},
    ('FLYING', 'ICE'): {'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 4, 'STEEL': 2},
    ('FLYING', 'FIGHTING'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'DARK': 0.5},
    ('FLYING', 'POISON'): {'ELECTRIC': 2, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.25, 'POISON': 0.5, 'GROUND': 0, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 2},
    ('FLYING', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'ICE': 4, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 0, 'BUG': 0.5},
    ('FLYING', 'PSYCHIC'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.25, 'GROUND': 0, 'PSYCHIC': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('FLYING', 'BUG'): {'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.25, 'GROUND': 0, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 4},
    ('FLYING', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 2, 'ICE': 2, 'POISON': 0.5, 'GROUND': 0, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('FLYING', 'GHOST'): {'NORMAL': 0, 'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 0, 'BUG': 0.25, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('FLYING', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'GRASS': 0.25, 'ICE': 4, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'DRAGON': 2},
    ('FLYING', 'DARK'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 0, 'PSYCHIC': 0, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5},
    ('FLYING', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'POISON': 0, 'GROUND': 0, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('PSYCHIC', None): {'FIGHTING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'NORMAL'): {'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 0, 'DARK': 2},
    ('PSYCHIC', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0.5, 'GROUND': 2, 'PSYCHIC': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('PSYCHIC', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('PSYCHIC', 'ELECTRIC'): {'ELECTRIC': 0.5, 'FIGHTING': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('PSYCHIC', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0.5, 'BUG': 4, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'ICE'): {'FIRE': 2, 'ICE': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('PSYCHIC', 'FIGHTING'): {'FIGHTING': 0.5, 'FLYING': 2, 'ROCK': 0.5, 'GHOST': 2},
    ('PSYCHIC', 'POISON'): {'GRASS': 0.5, 'FIGHTING': 0.25, 'POISON': 0.5, 'GROUND': 2, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 0.5, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'FLYING'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.25, 'GROUND': 0, 'PSYCHIC': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'BUG'): {'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0.25, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('PSYCHIC', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('PSYCHIC', 'GHOST'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'PSYCHIC': 0.5, 'GHOST': 4, 'DARK': 4},
    ('PSYCHIC', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DRAGON': 2, 'DARK': 2},
    ('PSYCHIC', 'DARK'): {'PSYCHIC': 0, 'BUG': 4},
    ('PSYCHIC', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.25, 'ROCK': 0.5, 'GHOST': 2, 'DRAGON': 0.5, 'DARK': 2, 'STEEL': 0.5},
    ('BUG', None): {'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2},
    ('BUG', 'NORMAL'): {'FIRE': 2, 'GRASS': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'GHOST': 0},
    ('BUG', 'FIRE'): {'WATER': 2, 'GRASS': 0.25, 'ICE': 0.5, 'FIGHTING': 0.5, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 4, 'STEEL': 0.5},
    ('BUG', 'WATER'): {'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.5, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'STEEL': 0.5},
    ('BUG', 'ELECTRIC'): {'FIRE': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 0.5, 'ROCK': 2, 'STEEL': 0.5},
    ('BUG', 'GRASS'): {'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 2, 'GROUND': 0.25, 'FLYING': 4, 'BUG': 2, 'ROCK': 2},
    ('BUG', 'ICE'): {'FIRE': 4, 'GRASS': 0.5, 'ICE': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 4, 'STEEL': 2},
    ('BUG', 'FIGHTING'): {'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 4, 'PSYCHIC': 2, 'BUG': 0.5, 'DARK': 0.5},
    ('BUG', 'POISON'): {'FIRE': 2, 'GRASS': 0.25, 'FIGHTING': 0.25, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 2},
    ('BUG', 'GROUND'): {'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 0.5, 'FLYING': 2},
    ('BUG', 'FLYING'): {'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.25, 'GROUND': 0, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 4},
    ('BUG', 'PSYCHIC'): {'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0.25, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0.5, 'BUG': 2, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('BUG', 'ROCK'): {'NORMAL': 0.5, 'WATER': 2, 'POISON': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('BUG', 'GHOST'): {'NORMAL': 0, 'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('BUG', 'DRAGON'): {'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'DRAGON': 2},
    ('BUG', 'DARK'): {'FIRE': 2, 'GRASS': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5},
    ('BUG', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 4, 'GRASS': 0.25, 'ICE': 0.5, 'POISON': 0, 'PSYCHIC': 0.5, 'BUG': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('ROCK', None): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'STEEL': 2},
    ('ROCK', 'NORMAL'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'GHOST': 0, 'STEEL': 2},
    ('ROCK', 'FIRE'): {'NORMAL': 0.5, 'FIRE': 0.25, 'WATER': 4, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2},
    ('ROCK', 'WATER'): {'NORMAL': 0.5, 'FIRE': 0.25, 'ELECTRIC': 2, 'GRASS': 4, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5},
    ('ROCK', 'ELECTRIC'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 0.5, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 4, 'FLYING': 0.25},
    ('ROCK', 'GRASS'): {'NORMAL': 0.5, 'ELECTRIC': 0.5, 'ICE': 2, 'FIGHTING': 2, 'BUG': 2, 'STEEL': 2},
    ('ROCK', 'ICE'): {'NORMAL': 0.5, 'WATER': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 2, 'STEEL': 4},
    ('ROCK', 'FIGHTING'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('ROCK', 'POISON'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'POISON': 0.25, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 2, 'BUG': 0.5, 'STEEL': 2},
    ('ROCK', 'GROUND'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 4, 'ELECTRIC': 0, 'GRASS': 4, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.25, 'GROUND': 2, 'FLYING': 0.5, 'ROCK': 0.5, 'STEEL': 2},
    ('ROCK', 'FLYING'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'ELECTRIC': 2, 'ICE': 2, 'POISON': 0.5, 'GROUND': 0, 'FLYING': 0.5, 'BUG': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('ROCK', 'PSYCHIC'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('ROCK', 'BUG'): {'NORMAL': 0.5, 'WATER': 2, 'POISON': 0.5, 'ROCK': 2, 'STEEL': 2},
    ('ROCK', 'GHOST'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 0, 'POISON': 0.25, 'GROUND': 2, 'FLYING': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('ROCK', 'DRAGON'): {'NORMAL': 0.5, 'FIRE': 0.25, 'ELECTRIC': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'DRAGON': 2, 'STEEL': 2},
    ('ROCK', 'DARK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('ROCK', 'STEEL'): {'NORMAL': 0.25, 'WATER': 2, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.25, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5},
    ('GHOST', None): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'NORMAL'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 0, 'DARK': 2},
    ('GHOST', 'FIRE'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 2, 'BUG': 0.25, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('GHOST', 'WATER'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('GHOST', 'ELECTRIC'): {'NORMAL': 0, 'ELECTRIC': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 0.5},
    ('GHOST', 'GRASS'): {'NORMAL': 0, 'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'GROUND': 0.5, 'FLYING': 2, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'ICE'): {'NORMAL': 0, 'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('GHOST', 'FIGHTING'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'ROCK': 0.5, 'GHOST': 2},
    ('GHOST', 'POISON'): {'NORMAL': 0, 'GRASS': 0.5, 'FIGHTING': 0, 'POISON': 0.25, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.25, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'GROUND'): {'NORMAL': 0, 'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.25, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'FLYING'): {'NORMAL': 0, 'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 0, 'BUG': 0.25, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'PSYCHIC'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'PSYCHIC': 0.5, 'GHOST': 4, 'DARK': 4},
    ('GHOST', 'BUG'): {'NORMAL': 0, 'FIRE': 2, 'GRASS': 0.5, 'FIGHTING': 0, 'POISON': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 0.5, 'ROCK': 2, 'GHOST': 2, 'DARK': 2},
    ('GHOST', 'ROCK'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 0, 'POISON': 0.25, 'GROUND': 2, 'FLYING': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DARK': 2, 'STEEL': 2},
    ('GHOST', 'DRAGON'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DRAGON': 2, 'DARK': 2},
    ('GHOST', 'DARK'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'PSYCHIC': 0},
    ('GHOST', 'STEEL'): {'NORMAL': 0, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'ROCK': 0.5, 'GHOST': 2, 'DRAGON': 0.5, 'DARK': 2, 'STEEL': 0.5},
    ('DRAGON', None): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'DRAGON': 2},
    ('DRAGON', 'NORMAL'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'GHOST': 0, 'DRAGON': 2},
    ('DRAGON', 'FIRE'): {'FIRE': 0.25, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'GROUND': 2, 'BUG': 0.5, 'ROCK': 2, 'DRAGON': 2, 'STEEL': 0.5},
    ('DRAGON', 'WATER'): {'FIRE': 0.25, 'WATER': 0.25, 'DRAGON': 2, 'STEEL': 0.5},
    ('DRAGON', 'ELECTRIC'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.25, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 2, 'FLYING': 0.5, 'DRAGON': 2, 'STEEL': 0.5},
    ('DRAGON', 'GRASS'): {'WATER': 0.25, 'ELECTRIC': 0.25, 'GRASS': 0.25, 'ICE': 4, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'BUG': 2, 'DRAGON': 2},
    ('DRAGON', 'ICE'): {'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'FIGHTING': 2, 'ROCK': 2, 'DRAGON': 2, 'STEEL': 2},
    ('DRAGON', 'FIGHTING'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FLYING': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 2, 'DARK': 0.5},
    ('DRAGON', 'POISON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 2, 'BUG': 0.5, 'DRAGON': 2},
    ('DRAGON', 'GROUND'): {'FIRE': 0.5, 'ELECTRIC': 0, 'ICE': 4, 'POISON': 0.5, 'ROCK': 0.5, 'DRAGON': 2},
    ('DRAGON', 'FLYING'): {'FIRE': 0.5, 'WATER': 0.5, 'GRASS': 0.25, 'ICE': 4, 'FIGHTING': 0.5, 'GROUND': 0, 'BUG': 0.5, 'ROCK': 2, 'DRAGON': 2},
    ('DRAGON', 'PSYCHIC'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0.5, 'PSYCHIC': 0.5, 'BUG': 2, 'GHOST': 2, 'DRAGON': 2, 'DARK': 2},
    ('DRAGON', 'BUG'): {'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'ICE': 2, 'FIGHTING': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'ROCK': 2, 'DRAGON': 2},
    ('DRAGON', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.25, 'ELECTRIC': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'DRAGON': 2, 'STEEL': 2},
    ('DRAGON', 'GHOST'): {'NORMAL': 0, 'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 0, 'POISON': 0.5, 'BUG': 0.5, 'GHOST': 2, 'DRAGON': 2, 'DARK': 2},
    ('DRAGON', 'DARK'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DRAGON': 2, 'DARK': 0.5},
    ('DRAGON', 'STEEL'): {'NORMAL': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('DARK', None): {'FIGHTING': 2, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'NORMAL'): {'FIGHTING': 4, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0, 'DARK': 0.5},
    ('DARK', 'FIRE'): {'FIRE': 0.5, 'WATER': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'PSYCHIC': 0, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('DARK', 'WATER'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'GRASS': 2, 'ICE': 0.5, 'FIGHTING': 2, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('DARK', 'ELECTRIC'): {'ELECTRIC': 0.5, 'FIGHTING': 2, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('DARK', 'GRASS'): {'FIRE': 2, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'POISON': 2, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0, 'BUG': 4, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'ICE'): {'FIRE': 2, 'ICE': 0.5, 'FIGHTING': 4, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('DARK', 'FIGHTING'): {'FIGHTING': 2, 'FLYING': 2, 'PSYCHIC': 0, 'ROCK': 0.5, 'GHOST': 0.5, 'DARK': 0.25},
    ('DARK', 'POISON'): {'GRASS': 0.5, 'POISON': 0.5, 'GROUND': 2, 'PSYCHIC': 0, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'GROUND'): {'WATER': 2, 'ELECTRIC': 0, 'GRASS': 2, 'ICE': 2, 'FIGHTING': 2, 'POISON': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 0.5, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'FLYING'): {'ELECTRIC': 2, 'GRASS': 0.5, 'ICE': 2, 'GROUND': 0, 'PSYCHIC': 0, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'PSYCHIC'): {'PSYCHIC': 0, 'BUG': 4},
    ('DARK', 'BUG'): {'FIRE': 2, 'GRASS': 0.5, 'GROUND': 0.5, 'FLYING': 2, 'PSYCHIC': 0, 'BUG': 2, 'ROCK': 2, 'GHOST': 0.5, 'DARK': 0.5},
    ('DARK', 'ROCK'): {'NORMAL': 0.5, 'FIRE': 0.5, 'WATER': 2, 'GRASS': 2, 'FIGHTING': 4, 'POISON': 0.5, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DARK': 0.5, 'STEEL': 2},
    ('DARK', 'GHOST'): {'NORMAL': 0, 'FIGHTING': 0, 'POISON': 0.5, 'PSYCHIC': 0},
    ('DARK', 'DRAGON'): {'FIRE': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 2, 'FIGHTING': 2, 'PSYCHIC': 0, 'BUG': 2, 'GHOST': 0.5, 'DRAGON': 2, 'DARK': 0.5},
    ('DARK', 'STEEL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'ROCK': 0.5, 'GHOST': 0.5, 'DRAGON': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('STEEL', None): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'NORMAL'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'GHOST': 0, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'FIRE'): {'NORMAL': 0.5, 'WATER': 2, 'GRASS': 0.25, 'ICE': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('STEEL', 'WATER'): {'NORMAL': 0.5, 'WATER': 0.5, 'ELECTRIC': 2, 'ICE': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('STEEL', 'ELECTRIC'): {'NORMAL': 0.5, 'FIRE': 2, 'ELECTRIC': 0.5, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.25, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.25},
    ('STEEL', 'GRASS'): {'NORMAL': 0.5, 'FIRE': 4, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'FIGHTING': 2, 'POISON': 0, 'PSYCHIC': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'ICE'): {'NORMAL': 0.5, 'FIRE': 4, 'GRASS': 0.5, 'ICE': 0.25, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'DRAGON': 0.5},
    ('STEEL', 'FIGHTING'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'BUG': 0.25, 'ROCK': 0.25, 'DRAGON': 0.5, 'DARK': 0.5, 'STEEL': 0.5},
    ('STEEL', 'POISON'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.25, 'ICE': 0.5, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.5, 'BUG': 0.25, 'ROCK': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'GROUND'): {'NORMAL': 0.5, 'FIRE': 2, 'WATER': 2, 'ELECTRIC': 0, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.25, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'FLYING'): {'NORMAL': 0.5, 'FIRE': 2, 'ELECTRIC': 2, 'GRASS': 0.25, 'POISON': 0, 'GROUND': 0, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'PSYCHIC'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.25, 'ROCK': 0.5, 'GHOST': 2, 'DRAGON': 0.5, 'DARK': 2, 'STEEL': 0.5},
    ('STEEL', 'BUG'): {'NORMAL': 0.5, 'FIRE': 4, 'GRASS': 0.25, 'ICE': 0.5, 'POISON': 0, 'PSYCHIC': 0.5, 'BUG': 0.5, 'DRAGON': 0.5, 'STEEL': 0.5},
    ('STEEL', 'ROCK'): {'NORMAL': 0.25, 'WATER': 2, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 4, 'FLYING': 0.25, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'DRAGON': 0.5},
    ('STEEL', 'GHOST'): {'NORMAL': 0, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 0, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.25, 'ROCK': 0.5, 'GHOST': 2, 'DRAGON': 0.5, 'DARK': 2, 'STEEL': 0.5},
    ('STEEL', 'DRAGON'): {'NORMAL': 0.5, 'WATER': 0.5, 'ELECTRIC': 0.5, 'GRASS': 0.25, 'FIGHTING': 2, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0.5, 'BUG': 0.5, 'ROCK': 0.5, 'STEEL': 0.5},
    ('STEEL', 'DARK'): {'NORMAL': 0.5, 'FIRE': 2, 'GRASS': 0.5, 'ICE': 0.5, 'FIGHTING': 4, 'POISON': 0, 'GROUND': 2, 'FLYING': 0.5, 'PSYCHIC': 0, 'ROCK': 0.5, 'GHOST': 0.5, 'DRAGON': 0.5, 'DARK': 0.5, 'STEEL': 0.5}
}