from .move import Move
from commons import Character
from .abstracts import MoveCategory as MC
from .abstracts import Type, Stat, Nature, Ability

HARDY  : Nature = Nature(name='Hardy', up_stat=Stat.ATTACK, down_stat=Stat.ATTACK)
LONELY : Nature = Nature(name='Lonely', up_stat=Stat.ATTACK, down_stat=Stat.DEFENSE)
BRAVE  : Nature = Nature(name='Brave', up_stat=Stat.ATTACK, down_stat=Stat.SPEED)
ADAMANT: Nature = Nature(name='Adamant', up_stat=Stat.ATTACK, down_stat=Stat.SPECIAL_ATTACK)
NAUGHTY: Nature = Nature(name='Naughty', up_stat=Stat.ATTACK, down_stat=Stat.SPECIAL_DEFENSE)
BOLD   : Nature = Nature(name='Bold', up_stat=Stat.DEFENSE, down_stat=Stat.ATTACK)
DOCILE : Nature = Nature(name='Docile', up_stat=Stat.DEFENSE, down_stat=Stat.DEFENSE)
RELAXED: Nature = Nature(name='Relaxed', up_stat=Stat.DEFENSE, down_stat=Stat.SPEED)
IMPISH : Nature = Nature(name='Impish', up_stat=Stat.DEFENSE, down_stat=Stat.SPECIAL_ATTACK)
LAX    : Nature = Nature(name='Lax', up_stat=Stat.DEFENSE, down_stat=Stat.SPECIAL_DEFENSE)
TIMID  : Nature = Nature(name='Timid', up_stat=Stat.SPEED, down_stat=Stat.ATTACK)
HASTY  : Nature = Nature(name='Hasty', up_stat=Stat.SPEED, down_stat=Stat.DEFENSE)
SERIOUS: Nature = Nature(name='Serious', up_stat=Stat.SPEED, down_stat=Stat.SPEED)
JOLLY  : Nature = Nature(name='Jolly', up_stat=Stat.SPEED, down_stat=Stat.SPECIAL_ATTACK)
NAIVE  : Nature = Nature(name='Naive', up_stat=Stat.SPEED, down_stat=Stat.SPECIAL_DEFENSE)
MODEST : Nature = Nature(name='Modest', up_stat=Stat.SPECIAL_ATTACK, down_stat=Stat.ATTACK)
MILD   : Nature = Nature(name='Mild', up_stat=Stat.SPECIAL_ATTACK, down_stat=Stat.DEFENSE)
QUIET  : Nature = Nature(name='Quiet', up_stat=Stat.SPECIAL_ATTACK, down_stat=Stat.SPEED)
BASHFUL: Nature = Nature(name='Bashful', up_stat=Stat.SPECIAL_ATTACK, down_stat=Stat.SPECIAL_ATTACK)
RASH   : Nature = Nature(name='Rash', up_stat=Stat.SPECIAL_ATTACK, down_stat=Stat.SPECIAL_DEFENSE)
CALM   : Nature = Nature(name='Calm', up_stat=Stat.SPECIAL_DEFENSE, down_stat=Stat.ATTACK)
GENTLE : Nature = Nature(name='Gentle', up_stat=Stat.SPECIAL_DEFENSE, down_stat=Stat.DEFENSE)
SASSY  : Nature = Nature(name='Sassy', up_stat=Stat.SPECIAL_DEFENSE, down_stat=Stat.SPEED)
CAREFUL: Nature = Nature(name='Careful', up_stat=Stat.SPECIAL_DEFENSE, down_stat=Stat.SPECIAL_ATTACK)
QUIRKY : Nature = Nature(name='Quirky', up_stat=Stat.SPECIAL_DEFENSE, down_stat=Stat.SPECIAL_DEFENSE)

COMBOS: dict[tuple[Type, Type | None], dict[Type, int | float]] = {
    (Type.NORMAL, None): {Type.FIGHTING: 2, Type.GHOST: 0},
    (Type.NORMAL, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.NORMAL, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.NORMAL, Type.ELECTRIC): {Type.ELECTRIC: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.NORMAL, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.GHOST: 0},
    (Type.NORMAL, Type.ICE): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.ROCK: 2, Type.GHOST: 0, Type.STEEL: 2},
    (Type.NORMAL, Type.FIGHTING): {Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 0, Type.DARK: 0.5},
    (Type.NORMAL, Type.POISON): {Type.GRASS: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.GHOST: 0},
    (Type.NORMAL, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.ROCK: 0.5, Type.GHOST: 0},
    (Type.NORMAL, Type.FLYING): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 0},
    (Type.NORMAL, Type.PSYCHIC): {Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 0, Type.DARK: 2},
    (Type.NORMAL, Type.BUG): {Type.FIRE: 2, Type.GRASS: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.GHOST: 0},
    (Type.NORMAL, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.GHOST: 0, Type.STEEL: 2},
    (Type.NORMAL, Type.GHOST): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 0, Type.DARK: 2},
    (Type.NORMAL, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.GHOST: 0, Type.DRAGON: 2},
    (Type.NORMAL, Type.DARK): {Type.FIGHTING: 4, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0, Type.DARK: 0.5},
    (Type.NORMAL, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 0, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.FIRE, None): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.NORMAL): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.FIRE, Type.WATER): {Type.FIRE: 0.25, Type.ELECTRIC: 2, Type.ICE: 0.25, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.25},
    (Type.FIRE, Type.ELECTRIC): {Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.25},
    (Type.FIRE, Type.GRASS): {Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.POISON: 2, Type.FLYING: 2, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.ICE): {Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.25, Type.FIGHTING: 2, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 4},
    (Type.FIRE, Type.FIGHTING): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.FIRE, Type.POISON): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 4, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.GROUND): {Type.FIRE: 0.5, Type.WATER: 4, Type.ELECTRIC: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.FIRE, Type.FLYING): {Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.25, Type.ROCK: 4, Type.STEEL: 0.5},
    (Type.FIRE, Type.PSYCHIC): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 2, Type.PSYCHIC: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.BUG): {Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 4, Type.STEEL: 0.5},
    (Type.FIRE, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.WATER: 4, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2},
    (Type.FIRE, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.BUG: 0.25, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.DRAGON): {Type.FIRE: 0.25, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.FIRE, Type.DARK): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.PSYCHIC: 0, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.FIRE, Type.STEEL): {Type.NORMAL: 0.5, Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.WATER, None): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.STEEL: 0.5},
    (Type.WATER, Type.NORMAL): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.WATER, Type.FIRE): {Type.FIRE: 0.25, Type.ELECTRIC: 2, Type.ICE: 0.25, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.25},
    (Type.WATER, Type.ELECTRIC): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.GRASS: 2, Type.ICE: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.STEEL: 0.25},
    (Type.WATER, Type.GRASS): {Type.WATER: 0.25, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.ICE): {Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.25, Type.FIGHTING: 2, Type.ROCK: 2},
    (Type.WATER, Type.FIGHTING): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.WATER, Type.POISON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.WATER, Type.GROUND): {Type.FIRE: 0.5, Type.ELECTRIC: 0, Type.GRASS: 4, Type.POISON: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.WATER, Type.FLYING): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 4, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.PSYCHIC): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.BUG): {Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.ELECTRIC: 2, Type.GRASS: 4, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5},
    (Type.WATER, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.DRAGON): {Type.FIRE: 0.25, Type.WATER: 0.25, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.WATER, Type.DARK): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.WATER, Type.STEEL): {Type.NORMAL: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.ELECTRIC, None): {Type.ELECTRIC: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.NORMAL): {Type.ELECTRIC: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.GHOST: 0, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.25},
    (Type.ELECTRIC, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.GRASS: 2, Type.ICE: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.STEEL: 0.25},
    (Type.ELECTRIC, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.25, Type.GRASS: 0.5, Type.ICE: 2, Type.POISON: 2, Type.BUG: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.ICE): {Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 2},
    (Type.ELECTRIC, Type.FIGHTING): {Type.ELECTRIC: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.POISON): {Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.FLYING): {Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.PSYCHIC): {Type.ELECTRIC: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.BUG): {Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 0.5, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.25},
    (Type.ELECTRIC, Type.GHOST): {Type.NORMAL: 0, Type.ELECTRIC: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.25, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.DARK): {Type.ELECTRIC: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.ELECTRIC, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.25, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.GRASS, None): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2},
    (Type.GRASS, Type.NORMAL): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.GHOST: 0},
    (Type.GRASS, Type.FIRE): {Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.POISON: 2, Type.FLYING: 2, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.GRASS, Type.WATER): {Type.WATER: 0.25, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.STEEL: 0.5},
    (Type.GRASS, Type.ELECTRIC): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.25, Type.GRASS: 0.5, Type.ICE: 2, Type.POISON: 2, Type.BUG: 2, Type.STEEL: 0.5},
    (Type.GRASS, Type.ICE): {Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.ROCK: 2, Type.STEEL: 2},
    (Type.GRASS, Type.FIGHTING): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 4, Type.PSYCHIC: 2, Type.ROCK: 0.5, Type.DARK: 0.5},
    (Type.GRASS, Type.POISON): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2},
    (Type.GRASS, Type.GROUND): {Type.FIRE: 2, Type.ELECTRIC: 0, Type.ICE: 4, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.ROCK: 0.5},
    (Type.GRASS, Type.FLYING): {Type.FIRE: 2, Type.WATER: 0.5, Type.GRASS: 0.25, Type.ICE: 4, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0, Type.FLYING: 2, Type.ROCK: 2},
    (Type.GRASS, Type.PSYCHIC): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0.5, Type.BUG: 4, Type.GHOST: 2, Type.DARK: 2},
    (Type.GRASS, Type.BUG): {Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0.25, Type.FLYING: 4, Type.BUG: 2, Type.ROCK: 2},
    (Type.GRASS, Type.ROCK): {Type.NORMAL: 0.5, Type.ELECTRIC: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.BUG: 2, Type.STEEL: 2},
    (Type.GRASS, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.GROUND: 0.5, Type.FLYING: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.GRASS, Type.DRAGON): {Type.WATER: 0.25, Type.ELECTRIC: 0.25, Type.GRASS: 0.25, Type.ICE: 4, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.DRAGON: 2},
    (Type.GRASS, Type.DARK): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0, Type.BUG: 4, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.GRASS, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.PSYCHIC: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.ICE, None): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.ROCK: 2, Type.STEEL: 2},
    (Type.ICE, Type.NORMAL): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.ROCK: 2, Type.GHOST: 0, Type.STEEL: 2},
    (Type.ICE, Type.FIRE): {Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.25, Type.FIGHTING: 2, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 4},
    (Type.ICE, Type.WATER): {Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.25, Type.FIGHTING: 2, Type.ROCK: 2},
    (Type.ICE, Type.ELECTRIC): {Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 2},
    (Type.ICE, Type.GRASS): {Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.ROCK: 2, Type.STEEL: 2},
    (Type.ICE, Type.FIGHTING): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.ICE, Type.POISON): {Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.ICE, Type.GROUND): {Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.STEEL: 2},
    (Type.ICE, Type.FLYING): {Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 4, Type.STEEL: 2},
    (Type.ICE, Type.PSYCHIC): {Type.FIRE: 2, Type.ICE: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.ICE, Type.BUG): {Type.FIRE: 4, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 4, Type.STEEL: 2},
    (Type.ICE, Type.ROCK): {Type.NORMAL: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 2, Type.STEEL: 4},
    (Type.ICE, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.ICE, Type.DRAGON): {Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 2, Type.ROCK: 2, Type.DRAGON: 2, Type.STEEL: 2},
    (Type.ICE, Type.DARK): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.ICE, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.GRASS: 0.5, Type.ICE: 0.25, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.DRAGON: 0.5},
    (Type.FIGHTING, None): {Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5},
    (Type.FIGHTING, Type.NORMAL): {Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 0, Type.DARK: 0.5},
    (Type.FIGHTING, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.FIGHTING, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.FIGHTING, Type.ELECTRIC): {Type.ELECTRIC: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.FIGHTING, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 4, Type.PSYCHIC: 2, Type.ROCK: 0.5, Type.DARK: 0.5},
    (Type.FIGHTING, Type.ICE): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.FIGHTING, Type.POISON): {Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 2, Type.PSYCHIC: 4, Type.BUG: 0.25, Type.ROCK: 0.5, Type.DARK: 0.5},
    (Type.FIGHTING, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.25, Type.DARK: 0.5},
    (Type.FIGHTING, Type.FLYING): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.DARK: 0.5},
    (Type.FIGHTING, Type.PSYCHIC): {Type.FIGHTING: 0.5, Type.FLYING: 2, Type.ROCK: 0.5, Type.GHOST: 2},
    (Type.FIGHTING, Type.BUG): {Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 4, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DARK: 0.5},
    (Type.FIGHTING, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.FIGHTING, Type.GHOST): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 0.5, Type.GHOST: 2},
    (Type.FIGHTING, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 2, Type.DARK: 0.5},
    (Type.FIGHTING, Type.DARK): {Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 0, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DARK: 0.25},
    (Type.FIGHTING, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.BUG: 0.25, Type.ROCK: 0.25, Type.DRAGON: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.POISON, None): {Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5},
    (Type.POISON, Type.NORMAL): {Type.GRASS: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.GHOST: 0},
    (Type.POISON, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 4, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.POISON, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.POISON, Type.ELECTRIC): {Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.POISON, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2},
    (Type.POISON, Type.ICE): {Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.POISON, Type.FIGHTING): {Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 2, Type.PSYCHIC: 4, Type.BUG: 0.25, Type.ROCK: 0.5, Type.DARK: 0.5},
    (Type.POISON, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.25, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5},
    (Type.POISON, Type.FLYING): {Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.GROUND: 0, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 2},
    (Type.POISON, Type.PSYCHIC): {Type.GRASS: 0.5, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.GROUND: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.POISON, Type.BUG): {Type.FIRE: 2, Type.GRASS: 0.25, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 2},
    (Type.POISON, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.POISON: 0.25, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 2},
    (Type.POISON, Type.GHOST): {Type.NORMAL: 0, Type.GRASS: 0.5, Type.FIGHTING: 0, Type.POISON: 0.25, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.GHOST: 2, Type.DARK: 2},
    (Type.POISON, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DRAGON: 2},
    (Type.POISON, Type.DARK): {Type.GRASS: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 0, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.POISON, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.25, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.GROUND, None): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.POISON: 0.5, Type.ROCK: 0.5},
    (Type.GROUND, Type.NORMAL): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.ROCK: 0.5, Type.GHOST: 0},
    (Type.GROUND, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 4, Type.ELECTRIC: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.BUG: 0.5, Type.STEEL: 0.5},
    (Type.GROUND, Type.WATER): {Type.FIRE: 0.5, Type.ELECTRIC: 0, Type.GRASS: 4, Type.POISON: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.GROUND, Type.ELECTRIC): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.GROUND, Type.GRASS): {Type.FIRE: 2, Type.ELECTRIC: 0, Type.ICE: 4, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.ROCK: 0.5},
    (Type.GROUND, Type.ICE): {Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.STEEL: 2},
    (Type.GROUND, Type.FIGHTING): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.25, Type.DARK: 0.5},
    (Type.GROUND, Type.POISON): {Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.25, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5},
    (Type.GROUND, Type.FLYING): {Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 4, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 0, Type.BUG: 0.5},
    (Type.GROUND, Type.PSYCHIC): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 0.5, Type.GHOST: 2, Type.DARK: 2},
    (Type.GROUND, Type.BUG): {Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 0.5, Type.FLYING: 2},
    (Type.GROUND, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 4, Type.ELECTRIC: 0, Type.GRASS: 4, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.25, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 0.5, Type.STEEL: 2},
    (Type.GROUND, Type.GHOST): {Type.NORMAL: 0, Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.25, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 2, Type.DARK: 2},
    (Type.GROUND, Type.DRAGON): {Type.FIRE: 0.5, Type.ELECTRIC: 0, Type.ICE: 4, Type.POISON: 0.5, Type.ROCK: 0.5, Type.DRAGON: 2},
    (Type.GROUND, Type.DARK): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.GROUND, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.FLYING, None): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2},
    (Type.FLYING, Type.NORMAL): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 0},
    (Type.FLYING, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.25, Type.ROCK: 4, Type.STEEL: 0.5},
    (Type.FLYING, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 4, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.FLYING, Type.ELECTRIC): {Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.FLYING, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.GRASS: 0.25, Type.ICE: 4, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0, Type.FLYING: 2, Type.ROCK: 2},
    (Type.FLYING, Type.ICE): {Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 4, Type.STEEL: 2},
    (Type.FLYING, Type.FIGHTING): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.DARK: 0.5},
    (Type.FLYING, Type.POISON): {Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.GROUND: 0, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 2},
    (Type.FLYING, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 4, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 0, Type.BUG: 0.5},
    (Type.FLYING, Type.PSYCHIC): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.25, Type.GROUND: 0, Type.PSYCHIC: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.FLYING, Type.BUG): {Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.25, Type.GROUND: 0, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 4},
    (Type.FLYING, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 2, Type.ICE: 2, Type.POISON: 0.5, Type.GROUND: 0, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.FLYING, Type.GHOST): {Type.NORMAL: 0, Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 0, Type.BUG: 0.25, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.FLYING, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.GRASS: 0.25, Type.ICE: 4, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.DRAGON: 2},
    (Type.FLYING, Type.DARK): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 0, Type.PSYCHIC: 0, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.FLYING, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.POISON: 0, Type.GROUND: 0, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.PSYCHIC, None): {Type.FIGHTING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.NORMAL): {Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 0, Type.DARK: 2},
    (Type.PSYCHIC, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 2, Type.PSYCHIC: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.PSYCHIC, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.PSYCHIC, Type.ELECTRIC): {Type.ELECTRIC: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.PSYCHIC, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0.5, Type.BUG: 4, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.ICE): {Type.FIRE: 2, Type.ICE: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.PSYCHIC, Type.FIGHTING): {Type.FIGHTING: 0.5, Type.FLYING: 2, Type.ROCK: 0.5, Type.GHOST: 2},
    (Type.PSYCHIC, Type.POISON): {Type.GRASS: 0.5, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.GROUND: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 0.5, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.FLYING): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.25, Type.GROUND: 0, Type.PSYCHIC: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.BUG): {Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0.25, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.PSYCHIC, Type.GHOST): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.PSYCHIC: 0.5, Type.GHOST: 4, Type.DARK: 4},
    (Type.PSYCHIC, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DRAGON: 2, Type.DARK: 2},
    (Type.PSYCHIC, Type.DARK): {Type.PSYCHIC: 0, Type.BUG: 4},
    (Type.PSYCHIC, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.25, Type.ROCK: 0.5, Type.GHOST: 2, Type.DRAGON: 0.5, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.BUG, None): {Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2},
    (Type.BUG, Type.NORMAL): {Type.FIRE: 2, Type.GRASS: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.GHOST: 0},
    (Type.BUG, Type.FIRE): {Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 4, Type.STEEL: 0.5},
    (Type.BUG, Type.WATER): {Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.BUG, Type.ELECTRIC): {Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.ROCK: 2, Type.STEEL: 0.5},
    (Type.BUG, Type.GRASS): {Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 2, Type.GROUND: 0.25, Type.FLYING: 4, Type.BUG: 2, Type.ROCK: 2},
    (Type.BUG, Type.ICE): {Type.FIRE: 4, Type.GRASS: 0.5, Type.ICE: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 4, Type.STEEL: 2},
    (Type.BUG, Type.FIGHTING): {Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 4, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DARK: 0.5},
    (Type.BUG, Type.POISON): {Type.FIRE: 2, Type.GRASS: 0.25, Type.FIGHTING: 0.25, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 2},
    (Type.BUG, Type.GROUND): {Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 0.5, Type.FLYING: 2},
    (Type.BUG, Type.FLYING): {Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.25, Type.GROUND: 0, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 4},
    (Type.BUG, Type.PSYCHIC): {Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0.25, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.BUG, Type.ROCK): {Type.NORMAL: 0.5, Type.WATER: 2, Type.POISON: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.BUG, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.BUG, Type.DRAGON): {Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.DRAGON: 2},
    (Type.BUG, Type.DARK): {Type.FIRE: 2, Type.GRASS: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.BUG, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.GRASS: 0.25, Type.ICE: 0.5, Type.POISON: 0, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.ROCK, None): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.STEEL: 2},
    (Type.ROCK, Type.NORMAL): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.GHOST: 0, Type.STEEL: 2},
    (Type.ROCK, Type.FIRE): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.WATER: 4, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2},
    (Type.ROCK, Type.WATER): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.ELECTRIC: 2, Type.GRASS: 4, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5},
    (Type.ROCK, Type.ELECTRIC): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 0.5, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 4, Type.FLYING: 0.25},
    (Type.ROCK, Type.GRASS): {Type.NORMAL: 0.5, Type.ELECTRIC: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.BUG: 2, Type.STEEL: 2},
    (Type.ROCK, Type.ICE): {Type.NORMAL: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 2, Type.STEEL: 4},
    (Type.ROCK, Type.FIGHTING): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.ROCK, Type.POISON): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.POISON: 0.25, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.STEEL: 2},
    (Type.ROCK, Type.GROUND): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 4, Type.ELECTRIC: 0, Type.GRASS: 4, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.25, Type.GROUND: 2, Type.FLYING: 0.5, Type.ROCK: 0.5, Type.STEEL: 2},
    (Type.ROCK, Type.FLYING): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.ELECTRIC: 2, Type.ICE: 2, Type.POISON: 0.5, Type.GROUND: 0, Type.FLYING: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.ROCK, Type.PSYCHIC): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.ROCK, Type.BUG): {Type.NORMAL: 0.5, Type.WATER: 2, Type.POISON: 0.5, Type.ROCK: 2, Type.STEEL: 2},
    (Type.ROCK, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 0, Type.POISON: 0.25, Type.GROUND: 2, Type.FLYING: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.ROCK, Type.DRAGON): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.ELECTRIC: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.DRAGON: 2, Type.STEEL: 2},
    (Type.ROCK, Type.DARK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.ROCK, Type.STEEL): {Type.NORMAL: 0.25, Type.WATER: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.25, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5},
    (Type.GHOST, None): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.NORMAL): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 0, Type.DARK: 2},
    (Type.GHOST, Type.FIRE): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.BUG: 0.25, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.GHOST, Type.WATER): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.GHOST, Type.ELECTRIC): {Type.NORMAL: 0, Type.ELECTRIC: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.GHOST, Type.GRASS): {Type.NORMAL: 0, Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.GROUND: 0.5, Type.FLYING: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.ICE): {Type.NORMAL: 0, Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.GHOST, Type.FIGHTING): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.ROCK: 0.5, Type.GHOST: 2},
    (Type.GHOST, Type.POISON): {Type.NORMAL: 0, Type.GRASS: 0.5, Type.FIGHTING: 0, Type.POISON: 0.25, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.25, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.GROUND): {Type.NORMAL: 0, Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.25, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.FLYING): {Type.NORMAL: 0, Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 0, Type.BUG: 0.25, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.PSYCHIC): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.PSYCHIC: 0.5, Type.GHOST: 4, Type.DARK: 4},
    (Type.GHOST, Type.BUG): {Type.NORMAL: 0, Type.FIRE: 2, Type.GRASS: 0.5, Type.FIGHTING: 0, Type.POISON: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.GHOST: 2, Type.DARK: 2},
    (Type.GHOST, Type.ROCK): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 0, Type.POISON: 0.25, Type.GROUND: 2, Type.FLYING: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DARK: 2, Type.STEEL: 2},
    (Type.GHOST, Type.DRAGON): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DRAGON: 2, Type.DARK: 2},
    (Type.GHOST, Type.DARK): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.PSYCHIC: 0},
    (Type.GHOST, Type.STEEL): {Type.NORMAL: 0, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.ROCK: 0.5, Type.GHOST: 2, Type.DRAGON: 0.5, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.DRAGON, None): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.DRAGON: 2},
    (Type.DRAGON, Type.NORMAL): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.GHOST: 0, Type.DRAGON: 2},
    (Type.DRAGON, Type.FIRE): {Type.FIRE: 0.25, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.GROUND: 2, Type.BUG: 0.5, Type.ROCK: 2, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.DRAGON, Type.WATER): {Type.FIRE: 0.25, Type.WATER: 0.25, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.DRAGON, Type.ELECTRIC): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.25, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.DRAGON: 2, Type.STEEL: 0.5},
    (Type.DRAGON, Type.GRASS): {Type.WATER: 0.25, Type.ELECTRIC: 0.25, Type.GRASS: 0.25, Type.ICE: 4, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.BUG: 2, Type.DRAGON: 2},
    (Type.DRAGON, Type.ICE): {Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.FIGHTING: 2, Type.ROCK: 2, Type.DRAGON: 2, Type.STEEL: 2},
    (Type.DRAGON, Type.FIGHTING): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FLYING: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 2, Type.DARK: 0.5},
    (Type.DRAGON, Type.POISON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 2, Type.BUG: 0.5, Type.DRAGON: 2},
    (Type.DRAGON, Type.GROUND): {Type.FIRE: 0.5, Type.ELECTRIC: 0, Type.ICE: 4, Type.POISON: 0.5, Type.ROCK: 0.5, Type.DRAGON: 2},
    (Type.DRAGON, Type.FLYING): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.GRASS: 0.25, Type.ICE: 4, Type.FIGHTING: 0.5, Type.GROUND: 0, Type.BUG: 0.5, Type.ROCK: 2, Type.DRAGON: 2},
    (Type.DRAGON, Type.PSYCHIC): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 2, Type.GHOST: 2, Type.DRAGON: 2, Type.DARK: 2},
    (Type.DRAGON, Type.BUG): {Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.ICE: 2, Type.FIGHTING: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.ROCK: 2, Type.DRAGON: 2},
    (Type.DRAGON, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.25, Type.ELECTRIC: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.DRAGON: 2, Type.STEEL: 2},
    (Type.DRAGON, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 0, Type.POISON: 0.5, Type.BUG: 0.5, Type.GHOST: 2, Type.DRAGON: 2, Type.DARK: 2},
    (Type.DRAGON, Type.DARK): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DRAGON: 2, Type.DARK: 0.5},
    (Type.DRAGON, Type.STEEL): {Type.NORMAL: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.DARK, None): {Type.FIGHTING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.NORMAL): {Type.FIGHTING: 4, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0, Type.DARK: 0.5},
    (Type.DARK, Type.FIRE): {Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.PSYCHIC: 0, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.DARK, Type.WATER): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.GRASS: 2, Type.ICE: 0.5, Type.FIGHTING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.DARK, Type.ELECTRIC): {Type.ELECTRIC: 0.5, Type.FIGHTING: 2, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.DARK, Type.GRASS): {Type.FIRE: 2, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 2, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0, Type.BUG: 4, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.ICE): {Type.FIRE: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.DARK, Type.FIGHTING): {Type.FIGHTING: 2, Type.FLYING: 2, Type.PSYCHIC: 0, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DARK: 0.25},
    (Type.DARK, Type.POISON): {Type.GRASS: 0.5, Type.POISON: 0.5, Type.GROUND: 2, Type.PSYCHIC: 0, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.GROUND): {Type.WATER: 2, Type.ELECTRIC: 0, Type.GRASS: 2, Type.ICE: 2, Type.FIGHTING: 2, Type.POISON: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.FLYING): {Type.ELECTRIC: 2, Type.GRASS: 0.5, Type.ICE: 2, Type.GROUND: 0, Type.PSYCHIC: 0, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.PSYCHIC): {Type.PSYCHIC: 0, Type.BUG: 4},
    (Type.DARK, Type.BUG): {Type.FIRE: 2, Type.GRASS: 0.5, Type.GROUND: 0.5, Type.FLYING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.ROCK: 2, Type.GHOST: 0.5, Type.DARK: 0.5},
    (Type.DARK, Type.ROCK): {Type.NORMAL: 0.5, Type.FIRE: 0.5, Type.WATER: 2, Type.GRASS: 2, Type.FIGHTING: 4, Type.POISON: 0.5, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DARK: 0.5, Type.STEEL: 2},
    (Type.DARK, Type.GHOST): {Type.NORMAL: 0, Type.FIGHTING: 0, Type.POISON: 0.5, Type.PSYCHIC: 0},
    (Type.DARK, Type.DRAGON): {Type.FIRE: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 2, Type.FIGHTING: 2, Type.PSYCHIC: 0, Type.BUG: 2, Type.GHOST: 0.5, Type.DRAGON: 2, Type.DARK: 0.5},
    (Type.DARK, Type.STEEL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DRAGON: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, None): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.NORMAL): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.GHOST: 0, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.FIRE): {Type.NORMAL: 0.5, Type.WATER: 2, Type.GRASS: 0.25, Type.ICE: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.STEEL, Type.WATER): {Type.NORMAL: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 2, Type.ICE: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.STEEL, Type.ELECTRIC): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.ELECTRIC: 0.5, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.25, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.25},
    (Type.STEEL, Type.GRASS): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.PSYCHIC: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.ICE): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.GRASS: 0.5, Type.ICE: 0.25, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.DRAGON: 0.5},
    (Type.STEEL, Type.FIGHTING): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.BUG: 0.25, Type.ROCK: 0.25, Type.DRAGON: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.POISON): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.25, Type.ICE: 0.5, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.5, Type.BUG: 0.25, Type.ROCK: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.GROUND): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.WATER: 2, Type.ELECTRIC: 0, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.FLYING): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.ELECTRIC: 2, Type.GRASS: 0.25, Type.POISON: 0, Type.GROUND: 0, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.PSYCHIC): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.25, Type.ROCK: 0.5, Type.GHOST: 2, Type.DRAGON: 0.5, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.STEEL, Type.BUG): {Type.NORMAL: 0.5, Type.FIRE: 4, Type.GRASS: 0.25, Type.ICE: 0.5, Type.POISON: 0, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.DRAGON: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.ROCK): {Type.NORMAL: 0.25, Type.WATER: 2, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 4, Type.FLYING: 0.25, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.DRAGON: 0.5},
    (Type.STEEL, Type.GHOST): {Type.NORMAL: 0, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 0, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.25, Type.ROCK: 0.5, Type.GHOST: 2, Type.DRAGON: 0.5, Type.DARK: 2, Type.STEEL: 0.5},
    (Type.STEEL, Type.DRAGON): {Type.NORMAL: 0.5, Type.WATER: 0.5, Type.ELECTRIC: 0.5, Type.GRASS: 0.25, Type.FIGHTING: 2, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0.5, Type.BUG: 0.5, Type.ROCK: 0.5, Type.STEEL: 0.5},
    (Type.STEEL, Type.DARK): {Type.NORMAL: 0.5, Type.FIRE: 2, Type.GRASS: 0.5, Type.ICE: 0.5, Type.FIGHTING: 4, Type.POISON: 0, Type.GROUND: 2, Type.FLYING: 0.5, Type.PSYCHIC: 0, Type.ROCK: 0.5, Type.GHOST: 0.5, Type.DRAGON: 0.5, Type.DARK: 0.5, Type.STEEL: 0.5},
}

OVERGROW: Ability = Ability("Overgrow", lambda: None)  # TODO

ABILITIES: list[Ability] = [
    OVERGROW
]

TACKLE: Move = Move(typing=Type.NORMAL, category=MC.PHYSICAL, PP=35,
              power=40, accuracy=100, contact=True, protect=True, mirror_move=True, kings_rock=True)

GROWL: Move = Move(typing=Type.NORMAL, category=MC.STATUS, PP=40, power=0, accuracy=100, contact=False,
             protect=True, mirror_move=True, kings_rock=False)

VINE_WHIP: Move = Move(typing=Type.GRASS, category=MC.PHYSICAL, PP=25, power=45, accuracy=100, contact=True,
                 protect=True, mirror_move=True, kings_rock=True)

LEECH_SEED: Move = Move(typing=Type.GRASS, category=MC.STATUS, PP=10, power=0, accuracy=90, contact=False,
                  protect=True, mirror_move=True, kings_rock=False)

PROFESSOR_OAK: Character = Character(name='Professor Oak', img='assets/characters/professor_oak.png')
